// Generated by Zap compiler, DO NOT EDIT
// source: lexer.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(91cc55cd57de5419);
ZAP_DECLARE_SCHEMA(c6725e678d60fa37);
ZAP_DECLARE_SCHEMA(9e69a92512b19d18);
ZAP_DECLARE_SCHEMA(a11f97b9d6c73dd4);

}  // namespace schemas
}  // namespace zap

namespace zap {
namespace compiler {

struct Token {
  Token() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    IDENTIFIER,
    STRING_LITERAL,
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    OPERATOR,
    PARENTHESIZED_LIST,
    BRACKETED_LIST,
    BINARY_LITERAL,
  };

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(91cc55cd57de5419, 3, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Statement {
  Statement() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    LINE,
    BLOCK,
  };

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(c6725e678d60fa37, 2, 3)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct LexedTokens {
  LexedTokens() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(9e69a92512b19d18, 0, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct LexedStatements {
  LexedStatements() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(a11f97b9d6c73dd4, 0, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

class Token::Reader {
public:
  typedef Token Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline Which which() const;
  inline bool isIdentifier() const;
  inline bool hasIdentifier() const;
  inline  ::zap::Text::Reader getIdentifier() const;

  inline bool isStringLiteral() const;
  inline bool hasStringLiteral() const;
  inline  ::zap::Text::Reader getStringLiteral() const;

  inline bool isIntegerLiteral() const;
  inline  ::uint64_t getIntegerLiteral() const;

  inline bool isFloatLiteral() const;
  inline double getFloatLiteral() const;

  inline bool isOperator() const;
  inline bool hasOperator() const;
  inline  ::zap::Text::Reader getOperator() const;

  inline bool isParenthesizedList() const;
  inline bool hasParenthesizedList() const;
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader getParenthesizedList() const;

  inline bool isBracketedList() const;
  inline bool hasBracketedList() const;
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader getBracketedList() const;

  inline  ::uint32_t getStartByte() const;

  inline  ::uint32_t getEndByte() const;

  inline bool isBinaryLiteral() const;
  inline bool hasBinaryLiteral() const;
  inline  ::zap::Data::Reader getBinaryLiteral() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Token::Builder {
public:
  typedef Token Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline Which which();
  inline bool isIdentifier();
  inline bool hasIdentifier();
  inline  ::zap::Text::Builder getIdentifier();
  inline void setIdentifier( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initIdentifier(unsigned int size);
  inline void adoptIdentifier(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownIdentifier();

  inline bool isStringLiteral();
  inline bool hasStringLiteral();
  inline  ::zap::Text::Builder getStringLiteral();
  inline void setStringLiteral( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initStringLiteral(unsigned int size);
  inline void adoptStringLiteral(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownStringLiteral();

  inline bool isIntegerLiteral();
  inline  ::uint64_t getIntegerLiteral();
  inline void setIntegerLiteral( ::uint64_t value);

  inline bool isFloatLiteral();
  inline double getFloatLiteral();
  inline void setFloatLiteral(double value);

  inline bool isOperator();
  inline bool hasOperator();
  inline  ::zap::Text::Builder getOperator();
  inline void setOperator( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initOperator(unsigned int size);
  inline void adoptOperator(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownOperator();

  inline bool isParenthesizedList();
  inline bool hasParenthesizedList();
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder getParenthesizedList();
  inline void setParenthesizedList( ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader value);
  inline void setParenthesizedList(::kj::ArrayPtr<const  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader> value);
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder initParenthesizedList(unsigned int size);
  inline void adoptParenthesizedList(::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>> disownParenthesizedList();

  inline bool isBracketedList();
  inline bool hasBracketedList();
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder getBracketedList();
  inline void setBracketedList( ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader value);
  inline void setBracketedList(::kj::ArrayPtr<const  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader> value);
  inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder initBracketedList(unsigned int size);
  inline void adoptBracketedList(::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>> disownBracketedList();

  inline  ::uint32_t getStartByte();
  inline void setStartByte( ::uint32_t value);

  inline  ::uint32_t getEndByte();
  inline void setEndByte( ::uint32_t value);

  inline bool isBinaryLiteral();
  inline bool hasBinaryLiteral();
  inline  ::zap::Data::Builder getBinaryLiteral();
  inline void setBinaryLiteral( ::zap::Data::Reader value);
  inline  ::zap::Data::Builder initBinaryLiteral(unsigned int size);
  inline void adoptBinaryLiteral(::zap::Orphan< ::zap::Data>&& value);
  inline ::zap::Orphan< ::zap::Data> disownBinaryLiteral();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Token::Pipeline {
public:
  typedef Token Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Statement::Reader {
public:
  typedef Statement Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline Which which() const;
  inline bool hasTokens() const;
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader getTokens() const;

  inline bool isLine() const;
  inline  ::zap::Void getLine() const;

  inline bool isBlock() const;
  inline bool hasBlock() const;
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader getBlock() const;

  inline bool hasDocComment() const;
  inline  ::zap::Text::Reader getDocComment() const;

  inline  ::uint32_t getStartByte() const;

  inline  ::uint32_t getEndByte() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Statement::Builder {
public:
  typedef Statement Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline Which which();
  inline bool hasTokens();
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder getTokens();
  inline void setTokens( ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder initTokens(unsigned int size);
  inline void adoptTokens(::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>> disownTokens();

  inline bool isLine();
  inline  ::zap::Void getLine();
  inline void setLine( ::zap::Void value = ::zap::VOID);

  inline bool isBlock();
  inline bool hasBlock();
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder getBlock();
  inline void setBlock( ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder initBlock(unsigned int size);
  inline void adoptBlock(::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>> disownBlock();

  inline bool hasDocComment();
  inline  ::zap::Text::Builder getDocComment();
  inline void setDocComment( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initDocComment(unsigned int size);
  inline void adoptDocComment(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownDocComment();

  inline  ::uint32_t getStartByte();
  inline void setStartByte( ::uint32_t value);

  inline  ::uint32_t getEndByte();
  inline void setEndByte( ::uint32_t value);

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Statement::Pipeline {
public:
  typedef Statement Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class LexedTokens::Reader {
public:
  typedef LexedTokens Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasTokens() const;
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader getTokens() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class LexedTokens::Builder {
public:
  typedef LexedTokens Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasTokens();
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder getTokens();
  inline void setTokens( ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder initTokens(unsigned int size);
  inline void adoptTokens(::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>> disownTokens();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class LexedTokens::Pipeline {
public:
  typedef LexedTokens Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class LexedStatements::Reader {
public:
  typedef LexedStatements Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasStatements() const;
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader getStatements() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class LexedStatements::Builder {
public:
  typedef LexedStatements Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasStatements();
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder getStatements();
  inline void setStatements( ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder initStatements(unsigned int size);
  inline void adoptStatements(::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>> disownStatements();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class LexedStatements::Pipeline {
public:
  typedef LexedStatements Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

inline  ::zap::compiler::Token::Which Token::Reader::which() const {
  return _reader.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline  ::zap::compiler::Token::Which Token::Builder::which() {
  return _builder.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline bool Token::Reader::isIdentifier() const {
  return which() == Token::IDENTIFIER;
}
inline bool Token::Builder::isIdentifier() {
  return which() == Token::IDENTIFIER;
}
inline bool Token::Reader::hasIdentifier() const {
  if (which() != Token::IDENTIFIER) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasIdentifier() {
  if (which() != Token::IDENTIFIER) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Token::Reader::getIdentifier() const {
  KJ_IREQUIRE((which() == Token::IDENTIFIER),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Token::Builder::getIdentifier() {
  KJ_IREQUIRE((which() == Token::IDENTIFIER),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setIdentifier( ::zap::Text::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::IDENTIFIER);
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Token::Builder::initIdentifier(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::IDENTIFIER);
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptIdentifier(
    ::zap::Orphan< ::zap::Text>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::IDENTIFIER);
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Token::Builder::disownIdentifier() {
  KJ_IREQUIRE((which() == Token::IDENTIFIER),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Token::Reader::isStringLiteral() const {
  return which() == Token::STRING_LITERAL;
}
inline bool Token::Builder::isStringLiteral() {
  return which() == Token::STRING_LITERAL;
}
inline bool Token::Reader::hasStringLiteral() const {
  if (which() != Token::STRING_LITERAL) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasStringLiteral() {
  if (which() != Token::STRING_LITERAL) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Token::Reader::getStringLiteral() const {
  KJ_IREQUIRE((which() == Token::STRING_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Token::Builder::getStringLiteral() {
  KJ_IREQUIRE((which() == Token::STRING_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setStringLiteral( ::zap::Text::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::STRING_LITERAL);
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Token::Builder::initStringLiteral(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::STRING_LITERAL);
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptStringLiteral(
    ::zap::Orphan< ::zap::Text>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::STRING_LITERAL);
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Token::Builder::disownStringLiteral() {
  KJ_IREQUIRE((which() == Token::STRING_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Token::Reader::isIntegerLiteral() const {
  return which() == Token::INTEGER_LITERAL;
}
inline bool Token::Builder::isIntegerLiteral() {
  return which() == Token::INTEGER_LITERAL;
}
inline  ::uint64_t Token::Reader::getIntegerLiteral() const {
  KJ_IREQUIRE((which() == Token::INTEGER_LITERAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::uint64_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}

inline  ::uint64_t Token::Builder::getIntegerLiteral() {
  KJ_IREQUIRE((which() == Token::INTEGER_LITERAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::uint64_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}
inline void Token::Builder::setIntegerLiteral( ::uint64_t value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::INTEGER_LITERAL);
  _builder.setDataField< ::uint64_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS, value);
}

inline bool Token::Reader::isFloatLiteral() const {
  return which() == Token::FLOAT_LITERAL;
}
inline bool Token::Builder::isFloatLiteral() {
  return which() == Token::FLOAT_LITERAL;
}
inline double Token::Reader::getFloatLiteral() const {
  KJ_IREQUIRE((which() == Token::FLOAT_LITERAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}

inline double Token::Builder::getFloatLiteral() {
  KJ_IREQUIRE((which() == Token::FLOAT_LITERAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}
inline void Token::Builder::setFloatLiteral(double value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::FLOAT_LITERAL);
  _builder.setDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS, value);
}

inline bool Token::Reader::isOperator() const {
  return which() == Token::OPERATOR;
}
inline bool Token::Builder::isOperator() {
  return which() == Token::OPERATOR;
}
inline bool Token::Reader::hasOperator() const {
  if (which() != Token::OPERATOR) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasOperator() {
  if (which() != Token::OPERATOR) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Token::Reader::getOperator() const {
  KJ_IREQUIRE((which() == Token::OPERATOR),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Token::Builder::getOperator() {
  KJ_IREQUIRE((which() == Token::OPERATOR),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setOperator( ::zap::Text::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::OPERATOR);
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Token::Builder::initOperator(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::OPERATOR);
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptOperator(
    ::zap::Orphan< ::zap::Text>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::OPERATOR);
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Token::Builder::disownOperator() {
  KJ_IREQUIRE((which() == Token::OPERATOR),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Token::Reader::isParenthesizedList() const {
  return which() == Token::PARENTHESIZED_LIST;
}
inline bool Token::Builder::isParenthesizedList() {
  return which() == Token::PARENTHESIZED_LIST;
}
inline bool Token::Reader::hasParenthesizedList() const {
  if (which() != Token::PARENTHESIZED_LIST) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasParenthesizedList() {
  if (which() != Token::PARENTHESIZED_LIST) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader Token::Reader::getParenthesizedList() const {
  KJ_IREQUIRE((which() == Token::PARENTHESIZED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder Token::Builder::getParenthesizedList() {
  KJ_IREQUIRE((which() == Token::PARENTHESIZED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setParenthesizedList( ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::PARENTHESIZED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline void Token::Builder::setParenthesizedList(::kj::ArrayPtr<const  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader> value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::PARENTHESIZED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder Token::Builder::initParenthesizedList(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::PARENTHESIZED_LIST);
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptParenthesizedList(
    ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::PARENTHESIZED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>> Token::Builder::disownParenthesizedList() {
  KJ_IREQUIRE((which() == Token::PARENTHESIZED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Token::Reader::isBracketedList() const {
  return which() == Token::BRACKETED_LIST;
}
inline bool Token::Builder::isBracketedList() {
  return which() == Token::BRACKETED_LIST;
}
inline bool Token::Reader::hasBracketedList() const {
  if (which() != Token::BRACKETED_LIST) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasBracketedList() {
  if (which() != Token::BRACKETED_LIST) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader Token::Reader::getBracketedList() const {
  KJ_IREQUIRE((which() == Token::BRACKETED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder Token::Builder::getBracketedList() {
  KJ_IREQUIRE((which() == Token::BRACKETED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setBracketedList( ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BRACKETED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline void Token::Builder::setBracketedList(::kj::ArrayPtr<const  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader> value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BRACKETED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>::Builder Token::Builder::initBracketedList(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BRACKETED_LIST);
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptBracketedList(
    ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BRACKETED_LIST);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>> Token::Builder::disownBracketedList() {
  KJ_IREQUIRE((which() == Token::BRACKETED_LIST),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>,  ::zap::Kind::LIST>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline  ::uint32_t Token::Reader::getStartByte() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}

inline  ::uint32_t Token::Builder::getStartByte() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}
inline void Token::Builder::setStartByte( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS, value);
}

inline  ::uint32_t Token::Reader::getEndByte() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<4>() * ::zap::ELEMENTS);
}

inline  ::uint32_t Token::Builder::getEndByte() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<4>() * ::zap::ELEMENTS);
}
inline void Token::Builder::setEndByte( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<4>() * ::zap::ELEMENTS, value);
}

inline bool Token::Reader::isBinaryLiteral() const {
  return which() == Token::BINARY_LITERAL;
}
inline bool Token::Builder::isBinaryLiteral() {
  return which() == Token::BINARY_LITERAL;
}
inline bool Token::Reader::hasBinaryLiteral() const {
  if (which() != Token::BINARY_LITERAL) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Token::Builder::hasBinaryLiteral() {
  if (which() != Token::BINARY_LITERAL) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Data::Reader Token::Reader::getBinaryLiteral() const {
  KJ_IREQUIRE((which() == Token::BINARY_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Data::Builder Token::Builder::getBinaryLiteral() {
  KJ_IREQUIRE((which() == Token::BINARY_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Token::Builder::setBinaryLiteral( ::zap::Data::Reader value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BINARY_LITERAL);
  ::zap::_::PointerHelpers< ::zap::Data>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Data::Builder Token::Builder::initBinaryLiteral(unsigned int size) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BINARY_LITERAL);
  return ::zap::_::PointerHelpers< ::zap::Data>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Token::Builder::adoptBinaryLiteral(
    ::zap::Orphan< ::zap::Data>&& value) {
  _builder.setDataField<Token::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Token::BINARY_LITERAL);
  ::zap::_::PointerHelpers< ::zap::Data>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Data> Token::Builder::disownBinaryLiteral() {
  KJ_IREQUIRE((which() == Token::BINARY_LITERAL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Data>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline  ::zap::compiler::Statement::Which Statement::Reader::which() const {
  return _reader.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline  ::zap::compiler::Statement::Which Statement::Builder::which() {
  return _builder.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline bool Statement::Reader::hasTokens() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Statement::Builder::hasTokens() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader Statement::Reader::getTokens() const {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder Statement::Builder::getTokens() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Statement::Builder::setTokens( ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder Statement::Builder::initTokens(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Statement::Builder::adoptTokens(
    ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>&& value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>> Statement::Builder::disownTokens() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Statement::Reader::isLine() const {
  return which() == Statement::LINE;
}
inline bool Statement::Builder::isLine() {
  return which() == Statement::LINE;
}
inline  ::zap::Void Statement::Reader::getLine() const {
  KJ_IREQUIRE((which() == Statement::LINE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::zap::Void Statement::Builder::getLine() {
  KJ_IREQUIRE((which() == Statement::LINE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void Statement::Builder::setLine( ::zap::Void value) {
  _builder.setDataField<Statement::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Statement::LINE);
  _builder.setDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline bool Statement::Reader::isBlock() const {
  return which() == Statement::BLOCK;
}
inline bool Statement::Builder::isBlock() {
  return which() == Statement::BLOCK;
}
inline bool Statement::Reader::hasBlock() const {
  if (which() != Statement::BLOCK) return false;
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool Statement::Builder::hasBlock() {
  if (which() != Statement::BLOCK) return false;
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader Statement::Reader::getBlock() const {
  KJ_IREQUIRE((which() == Statement::BLOCK),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder Statement::Builder::getBlock() {
  KJ_IREQUIRE((which() == Statement::BLOCK),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void Statement::Builder::setBlock( ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Statement::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Statement::BLOCK);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder Statement::Builder::initBlock(unsigned int size) {
  _builder.setDataField<Statement::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Statement::BLOCK);
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), size);
}
inline void Statement::Builder::adoptBlock(
    ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>&& value) {
  _builder.setDataField<Statement::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Statement::BLOCK);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>> Statement::Builder::disownBlock() {
  KJ_IREQUIRE((which() == Statement::BLOCK),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

inline bool Statement::Reader::hasDocComment() const {
  return !_reader.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS).isNull();
}
inline bool Statement::Builder::hasDocComment() {
  return !_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Statement::Reader::getDocComment() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Statement::Builder::getDocComment() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}
inline void Statement::Builder::setDocComment( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Statement::Builder::initDocComment(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), size);
}
inline void Statement::Builder::adoptDocComment(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Statement::Builder::disownDocComment() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}

inline  ::uint32_t Statement::Reader::getStartByte() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}

inline  ::uint32_t Statement::Builder::getStartByte() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}
inline void Statement::Builder::setStartByte( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<1>() * ::zap::ELEMENTS, value);
}

inline  ::uint32_t Statement::Reader::getEndByte() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS);
}

inline  ::uint32_t Statement::Builder::getEndByte() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS);
}
inline void Statement::Builder::setEndByte( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS, value);
}

inline bool LexedTokens::Reader::hasTokens() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool LexedTokens::Builder::hasTokens() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader LexedTokens::Reader::getTokens() const {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder LexedTokens::Builder::getTokens() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void LexedTokens::Builder::setTokens( ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Reader value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>::Builder LexedTokens::Builder::initTokens(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void LexedTokens::Builder::adoptTokens(
    ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>&& value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>> LexedTokens::Builder::disownTokens() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Token,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool LexedStatements::Reader::hasStatements() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool LexedStatements::Builder::hasStatements() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader LexedStatements::Reader::getStatements() const {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder LexedStatements::Builder::getStatements() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void LexedStatements::Builder::setStatements( ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Reader value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>::Builder LexedStatements::Builder::initStatements(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void LexedStatements::Builder::adoptStatements(
    ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>&& value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>> LexedStatements::Builder::disownStatements() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::compiler::Statement,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

}  // namespace
}  // namespace

ZAP_END_HEADER

