// Generated by Zap compiler, DO NOT EDIT
// source: c++.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(b9c6f99ebf805f2c);
ZAP_DECLARE_SCHEMA(f264a779fef191ce);
ZAP_DECLARE_SCHEMA(ac7096ff8cfc9dce);

}  // namespace schemas
}  // namespace zap

namespace zap {
namespace annotations {

// =======================================================================================

// =======================================================================================

}  // namespace
}  // namespace

ZAP_END_HEADER

