// Generated by Zap compiler, DO NOT EDIT
// source: persistent.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>
#if !ZAP_LITE
#include <zap/capability.h>
#endif  // !ZAP_LITE

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(c8cb212fcd9f5691);
ZAP_DECLARE_SCHEMA(f76fba59183073a5);
ZAP_DECLARE_SCHEMA(b76848c18c40efbf);
ZAP_DECLARE_SCHEMA(f622595091cafb67);

}  // namespace schemas
}  // namespace zap

namespace zap {

template <typename SturdyRef = ::zap::AnyPointer, typename Owner = ::zap::AnyPointer>
struct Persistent {
  Persistent() = delete;

#if !ZAP_LITE
  class Client;
  class Server;
#endif  // !ZAP_LITE

  struct SaveParams;
  struct SaveResults;

  #if !ZAP_LITE
  struct _zapPrivate {
    ZAP_DECLARE_INTERFACE_HEADER(c8cb212fcd9f5691)
    static const ::zap::_::RawBrandedSchema::Scope brandScopes[];
    static const ::zap::_::RawBrandedSchema::Binding brandBindings[];
    static const ::zap::_::RawBrandedSchema::Dependency brandDependencies[];
    static const ::zap::_::RawBrandedSchema specificBrand;
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return ::zap::_::ChooseBrand<_zapPrivate, SturdyRef, Owner>::brand(); }
  };
  #endif  // !ZAP_LITE
};

template <typename SturdyRef, typename Owner>
struct Persistent<SturdyRef, Owner>::SaveParams {
  SaveParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(f76fba59183073a5, 0, 1)
    #if !ZAP_LITE
    static const ::zap::_::RawBrandedSchema::Scope brandScopes[];
    static const ::zap::_::RawBrandedSchema::Binding brandBindings[];
    static const ::zap::_::RawBrandedSchema specificBrand;
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return ::zap::_::ChooseBrand<_zapPrivate, SturdyRef, Owner>::brand(); }
    #endif  // !ZAP_LITE
  };
};

template <typename SturdyRef, typename Owner>
struct Persistent<SturdyRef, Owner>::SaveResults {
  SaveResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(b76848c18c40efbf, 0, 1)
    #if !ZAP_LITE
    static const ::zap::_::RawBrandedSchema::Scope brandScopes[];
    static const ::zap::_::RawBrandedSchema::Binding brandBindings[];
    static const ::zap::_::RawBrandedSchema specificBrand;
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return ::zap::_::ChooseBrand<_zapPrivate, SturdyRef, Owner>::brand(); }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::Client
    : public virtual ::zap::Capability::Client {
public:
  typedef Persistent Calls;
  typedef Persistent Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::zap::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Rc<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  template <typename SturdyRef2 = ::zap::AnyPointer, typename Owner2 = ::zap::AnyPointer>
  typename Persistent<SturdyRef2, Owner2>::Client asGeneric() {
    return castAs<Persistent<SturdyRef2, Owner2>>();
  }

  ZAP_AUTO_IF_MSVC(::zap::Request<typename  ::zap::Persistent<SturdyRef, Owner>::SaveParams, typename  ::zap::Persistent<SturdyRef, Owner>::SaveResults>) saveRequest(
      ::kj::Maybe< ::zap::MessageSize> sizeHint = kj::none);

protected:
  Client() = default;
};

template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::Server
    : public virtual ::zap::Capability::Server {
public:
  typedef Persistent Serves;

  ::zap::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context)
      override;

protected:
  typedef ::zap::CallContext<typename  ::zap::Persistent<SturdyRef, Owner>::SaveParams, typename  ::zap::Persistent<SturdyRef, Owner>::SaveResults> SaveContext;
  virtual ::kj::Promise<void> save(SaveContext context);

  inline typename  ::zap::Persistent<SturdyRef, Owner>::Client thisCap() {
    return ::zap::Capability::Server::thisCap()
        .template castAs< ::zap::Persistent<SturdyRef, Owner>>();
  }

  ::zap::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context);
};
#endif  // !ZAP_LITE

template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveParams::Reader {
public:
  typedef SaveParams Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  template <typename SturdyRef2 = ::zap::AnyPointer, typename Owner2 = ::zap::AnyPointer>
  typename Persistent<SturdyRef2, Owner2>::SaveParams::Reader asPersistentGeneric() const {
    return typename Persistent<SturdyRef2, Owner2>::SaveParams::Reader(_reader);
  }

  inline bool hasSealFor() const;
  inline  ::zap::ReaderFor<Owner> getSealFor() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveParams::Builder {
public:
  typedef SaveParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  template <typename SturdyRef2 = ::zap::AnyPointer, typename Owner2 = ::zap::AnyPointer>
  typename Persistent<SturdyRef2, Owner2>::SaveParams::Builder asPersistentGeneric() {
    return typename Persistent<SturdyRef2, Owner2>::SaveParams::Builder(_builder);
  }

  inline bool hasSealFor();
  inline  ::zap::BuilderFor<Owner> getSealFor();
  inline void setSealFor( ::zap::ReaderFor<Owner> value);
  inline  ::zap::BuilderFor<Owner> initSealFor();
  inline  ::zap::BuilderFor<Owner> initSealFor(unsigned int size);
  inline void adoptSealFor(::zap::Orphan<Owner>&& value);
  inline ::zap::Orphan<Owner> disownSealFor();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveParams::Pipeline {
public:
  typedef SaveParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::zap::PipelineFor<Owner> getSealFor();
private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveResults::Reader {
public:
  typedef SaveResults Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  template <typename SturdyRef2 = ::zap::AnyPointer, typename Owner2 = ::zap::AnyPointer>
  typename Persistent<SturdyRef2, Owner2>::SaveResults::Reader asPersistentGeneric() const {
    return typename Persistent<SturdyRef2, Owner2>::SaveResults::Reader(_reader);
  }

  inline bool hasSturdyRef() const;
  inline  ::zap::ReaderFor<SturdyRef> getSturdyRef() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveResults::Builder {
public:
  typedef SaveResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  template <typename SturdyRef2 = ::zap::AnyPointer, typename Owner2 = ::zap::AnyPointer>
  typename Persistent<SturdyRef2, Owner2>::SaveResults::Builder asPersistentGeneric() {
    return typename Persistent<SturdyRef2, Owner2>::SaveResults::Builder(_builder);
  }

  inline bool hasSturdyRef();
  inline  ::zap::BuilderFor<SturdyRef> getSturdyRef();
  inline void setSturdyRef( ::zap::ReaderFor<SturdyRef> value);
  inline  ::zap::BuilderFor<SturdyRef> initSturdyRef();
  inline  ::zap::BuilderFor<SturdyRef> initSturdyRef(unsigned int size);
  inline void adoptSturdyRef(::zap::Orphan<SturdyRef>&& value);
  inline ::zap::Orphan<SturdyRef> disownSturdyRef();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
class Persistent<SturdyRef, Owner>::SaveResults::Pipeline {
public:
  typedef SaveResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::zap::PipelineFor<SturdyRef> getSturdyRef();
private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline Persistent<SturdyRef, Owner>::Client::Client(decltype(nullptr))
    : ::zap::Capability::Client(nullptr) {}
template <typename SturdyRef, typename Owner>
inline Persistent<SturdyRef, Owner>::Client::Client(
    ::kj::Own< ::zap::ClientHook>&& hook)
    : ::zap::Capability::Client(::kj::mv(hook)) {}
template <typename SturdyRef, typename Owner>
template <typename _t, typename>
inline Persistent<SturdyRef, Owner>::Client::Client(::kj::Own<_t>&& server)
    : ::zap::Capability::Client(::kj::mv(server)) {}
template <typename SturdyRef, typename Owner>
template <typename _t, typename>
inline Persistent<SturdyRef, Owner>::Client::Client(::kj::Rc<_t>&& server)
    : ::zap::Capability::Client(server.toOwn()) {}
template <typename SturdyRef, typename Owner>
template <typename _t, typename>
inline Persistent<SturdyRef, Owner>::Client::Client(::kj::Promise<_t>&& promise)
    : ::zap::Capability::Client(::kj::mv(promise)) {}
template <typename SturdyRef, typename Owner>
inline Persistent<SturdyRef, Owner>::Client::Client(::kj::Exception&& exception)
    : ::zap::Capability::Client(::kj::mv(exception)) {}
template <typename SturdyRef, typename Owner>
inline typename  ::zap::Persistent<SturdyRef, Owner>::Client& Persistent<SturdyRef, Owner>::Client::operator=(Client& other) {
  ::zap::Capability::Client::operator=(other);
  return *this;
}
template <typename SturdyRef, typename Owner>
inline typename  ::zap::Persistent<SturdyRef, Owner>::Client& Persistent<SturdyRef, Owner>::Client::operator=(Client&& other) {
  ::zap::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline bool Persistent<SturdyRef, Owner>::SaveParams::Reader::hasSealFor() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
template <typename SturdyRef, typename Owner>
inline bool Persistent<SturdyRef, Owner>::SaveParams::Builder::hasSealFor() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
template <typename SturdyRef, typename Owner>
inline  ::zap::ReaderFor<Owner> Persistent<SturdyRef, Owner>::SaveParams::Reader::getSealFor() const {
  return ::zap::_::PointerHelpers<Owner>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<Owner> Persistent<SturdyRef, Owner>::SaveParams::Builder::getSealFor() {
  return ::zap::_::PointerHelpers<Owner>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline  ::zap::PipelineFor<Owner> Persistent<SturdyRef, Owner>::SaveParams::Pipeline::getSealFor() {
  return  ::zap::PipelineFor<Owner>(_typeless.getPointerField(0));
}
#endif  // !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline void Persistent<SturdyRef, Owner>::SaveParams::Builder::setSealFor( ::zap::ReaderFor<Owner> value) {
  ::zap::_::PointerHelpers<Owner>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<Owner> Persistent<SturdyRef, Owner>::SaveParams::Builder::initSealFor() {
  return ::zap::_::PointerHelpers<Owner>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<Owner> Persistent<SturdyRef, Owner>::SaveParams::Builder::initSealFor(unsigned int size) {
  return ::zap::_::PointerHelpers<Owner>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
template <typename SturdyRef, typename Owner>
inline void Persistent<SturdyRef, Owner>::SaveParams::Builder::adoptSealFor(
    ::zap::Orphan<Owner>&& value) {
  ::zap::_::PointerHelpers<Owner>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
template <typename SturdyRef, typename Owner>
inline ::zap::Orphan<Owner> Persistent<SturdyRef, Owner>::SaveParams::Builder::disownSealFor() {
  return ::zap::_::PointerHelpers<Owner>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

// Persistent<SturdyRef, Owner>::SaveParams
#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Scope Persistent<SturdyRef, Owner>::SaveParams::_zapPrivate::brandScopes[] = {
  { 0xc8cb212fcd9f5691, brandBindings + 0, 2, false},
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Binding Persistent<SturdyRef, Owner>::SaveParams::_zapPrivate::brandBindings[] = {
  ::zap::_::brandBindingFor<SturdyRef>(),
  ::zap::_::brandBindingFor<Owner>(),
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema Persistent<SturdyRef, Owner>::SaveParams::_zapPrivate::specificBrand = {
  &::zap::schemas::s_f76fba59183073a5, brandScopes, nullptr,
  1, 0, nullptr
};
#endif  // !ZAP_LITE

template <typename SturdyRef, typename Owner>
inline bool Persistent<SturdyRef, Owner>::SaveResults::Reader::hasSturdyRef() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
template <typename SturdyRef, typename Owner>
inline bool Persistent<SturdyRef, Owner>::SaveResults::Builder::hasSturdyRef() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
template <typename SturdyRef, typename Owner>
inline  ::zap::ReaderFor<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Reader::getSturdyRef() const {
  return ::zap::_::PointerHelpers<SturdyRef>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Builder::getSturdyRef() {
  return ::zap::_::PointerHelpers<SturdyRef>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline  ::zap::PipelineFor<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Pipeline::getSturdyRef() {
  return  ::zap::PipelineFor<SturdyRef>(_typeless.getPointerField(0));
}
#endif  // !ZAP_LITE
template <typename SturdyRef, typename Owner>
inline void Persistent<SturdyRef, Owner>::SaveResults::Builder::setSturdyRef( ::zap::ReaderFor<SturdyRef> value) {
  ::zap::_::PointerHelpers<SturdyRef>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Builder::initSturdyRef() {
  return ::zap::_::PointerHelpers<SturdyRef>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
template <typename SturdyRef, typename Owner>
inline  ::zap::BuilderFor<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Builder::initSturdyRef(unsigned int size) {
  return ::zap::_::PointerHelpers<SturdyRef>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
template <typename SturdyRef, typename Owner>
inline void Persistent<SturdyRef, Owner>::SaveResults::Builder::adoptSturdyRef(
    ::zap::Orphan<SturdyRef>&& value) {
  ::zap::_::PointerHelpers<SturdyRef>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
template <typename SturdyRef, typename Owner>
inline ::zap::Orphan<SturdyRef> Persistent<SturdyRef, Owner>::SaveResults::Builder::disownSturdyRef() {
  return ::zap::_::PointerHelpers<SturdyRef>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

// Persistent<SturdyRef, Owner>::SaveResults
#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Scope Persistent<SturdyRef, Owner>::SaveResults::_zapPrivate::brandScopes[] = {
  { 0xc8cb212fcd9f5691, brandBindings + 0, 2, false},
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Binding Persistent<SturdyRef, Owner>::SaveResults::_zapPrivate::brandBindings[] = {
  ::zap::_::brandBindingFor<SturdyRef>(),
  ::zap::_::brandBindingFor<Owner>(),
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema Persistent<SturdyRef, Owner>::SaveResults::_zapPrivate::specificBrand = {
  &::zap::schemas::s_b76848c18c40efbf, brandScopes, nullptr,
  1, 0, nullptr
};
#endif  // !ZAP_LITE

#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
ZAP_AUTO_IF_MSVC(::zap::Request<typename  ::zap::Persistent<SturdyRef, Owner>::SaveParams, typename  ::zap::Persistent<SturdyRef, Owner>::SaveResults>)
Persistent<SturdyRef, Owner>::Client::saveRequest(::kj::Maybe< ::zap::MessageSize> sizeHint) {
  return newCall<typename  ::zap::Persistent<SturdyRef, Owner>::SaveParams, typename  ::zap::Persistent<SturdyRef, Owner>::SaveResults>(
      0xc8cb212fcd9f5691ull, 0, sizeHint, {false});
}
template <typename SturdyRef, typename Owner>
::kj::Promise<void> Persistent<SturdyRef, Owner>::Server::save(SaveContext) {
  return ::zap::Capability::Server::internalUnimplemented(
      "zap/persistent.zap:Persistent", "save",
      0xc8cb212fcd9f5691ull, 0);
}
template <typename SturdyRef, typename Owner>
::zap::Capability::Server::DispatchCallResult Persistent<SturdyRef, Owner>::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context) {
  switch (interfaceId) {
    case 0xc8cb212fcd9f5691ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("zap/persistent.zap:Persistent", interfaceId);
  }
}
template <typename SturdyRef, typename Owner>
::zap::Capability::Server::DispatchCallResult Persistent<SturdyRef, Owner>::Server::dispatchCallInternal(
    uint16_t methodId,
    ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        save(::zap::Capability::Server::internalGetTypedContext<
            typename  ::zap::Persistent<SturdyRef, Owner>::SaveParams, typename  ::zap::Persistent<SturdyRef, Owner>::SaveResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::zap::Capability::Server::internalUnimplemented(
          "zap/persistent.zap:Persistent",
          0xc8cb212fcd9f5691ull, methodId);
  }
}
#endif  // !ZAP_LITE

// Persistent<SturdyRef, Owner>
#if !ZAP_LITE
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Scope Persistent<SturdyRef, Owner>::_zapPrivate::brandScopes[] = {
  { 0xc8cb212fcd9f5691, brandBindings + 0, 2, false},
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Binding Persistent<SturdyRef, Owner>::_zapPrivate::brandBindings[] = {
  ::zap::_::brandBindingFor<SturdyRef>(),
  ::zap::_::brandBindingFor<Owner>(),
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema::Dependency Persistent<SturdyRef, Owner>::_zapPrivate::brandDependencies[] = {
  { 33554432,  ::zap::Persistent<SturdyRef, Owner>::SaveParams::_zapPrivate::brand() },
  { 50331648,  ::zap::Persistent<SturdyRef, Owner>::SaveResults::_zapPrivate::brand() },
};
template <typename SturdyRef, typename Owner>
const ::zap::_::RawBrandedSchema Persistent<SturdyRef, Owner>::_zapPrivate::specificBrand = {
  &::zap::schemas::s_c8cb212fcd9f5691, brandScopes, brandDependencies,
  1, 2, nullptr
};
#endif  // !ZAP_LITE

}  // namespace

ZAP_END_HEADER

