// Generated by Zap compiler, DO NOT EDIT
// source: rpc-twoparty.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>
#if !ZAP_LITE
#include <zap/capability.h>
#endif  // !ZAP_LITE

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(9fd69ebc87b9719c);
enum class Side_9fd69ebc87b9719c: uint16_t {
  SERVER,
  CLIENT,
};
ZAP_DECLARE_ENUM(Side, 9fd69ebc87b9719c);
ZAP_DECLARE_SCHEMA(d20b909fee733a8e);
ZAP_DECLARE_SCHEMA(b7e329e92fda637d);
ZAP_DECLARE_SCHEMA(9539708bffa85a5d);
ZAP_DECLARE_SCHEMA(e8e97b3b9f049b21);
ZAP_DECLARE_SCHEMA(95b29059097fca83);
ZAP_DECLARE_SCHEMA(9d263a3630b7ebee);

}  // namespace schemas
}  // namespace zap

namespace zap {
namespace rpc {
namespace twoparty {

typedef ::zap::schemas::Side_9fd69ebc87b9719c Side;

struct VatId {
  VatId() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(d20b909fee733a8e, 1, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct ThirdPartyCompletion {
  ThirdPartyCompletion() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(b7e329e92fda637d, 1, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct ThirdPartyToAwait {
  ThirdPartyToAwait() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(9539708bffa85a5d, 0, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct ThirdPartyToContact {
  ThirdPartyToContact() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(e8e97b3b9f049b21, 0, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct JoinKeyPart {
  JoinKeyPart() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(95b29059097fca83, 1, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct JoinResult {
  JoinResult() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(9d263a3630b7ebee, 1, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

class VatId::Reader {
public:
  typedef VatId Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline  ::zap::rpc::twoparty::Side getSide() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class VatId::Builder {
public:
  typedef VatId Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline  ::zap::rpc::twoparty::Side getSide();
  inline void setSide( ::zap::rpc::twoparty::Side value);

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class VatId::Pipeline {
public:
  typedef VatId Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class ThirdPartyCompletion::Reader {
public:
  typedef ThirdPartyCompletion Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class ThirdPartyCompletion::Builder {
public:
  typedef ThirdPartyCompletion Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId();
  inline void setJoinId( ::uint32_t value);

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class ThirdPartyCompletion::Pipeline {
public:
  typedef ThirdPartyCompletion Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class ThirdPartyToAwait::Reader {
public:
  typedef ThirdPartyToAwait Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class ThirdPartyToAwait::Builder {
public:
  typedef ThirdPartyToAwait Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class ThirdPartyToAwait::Pipeline {
public:
  typedef ThirdPartyToAwait Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class ThirdPartyToContact::Reader {
public:
  typedef ThirdPartyToContact Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class ThirdPartyToContact::Builder {
public:
  typedef ThirdPartyToContact Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class ThirdPartyToContact::Pipeline {
public:
  typedef ThirdPartyToContact Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class JoinKeyPart::Reader {
public:
  typedef JoinKeyPart Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId() const;

  inline  ::uint16_t getPartCount() const;

  inline  ::uint16_t getPartNum() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class JoinKeyPart::Builder {
public:
  typedef JoinKeyPart Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId();
  inline void setJoinId( ::uint32_t value);

  inline  ::uint16_t getPartCount();
  inline void setPartCount( ::uint16_t value);

  inline  ::uint16_t getPartNum();
  inline void setPartNum( ::uint16_t value);

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class JoinKeyPart::Pipeline {
public:
  typedef JoinKeyPart Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class JoinResult::Reader {
public:
  typedef JoinResult Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId() const;

  inline bool getSucceeded() const;

  inline bool hasCap() const;
#if !ZAP_LITE
  inline  ::zap::Capability::Client getCap() const;
#endif  // !ZAP_LITE

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class JoinResult::Builder {
public:
  typedef JoinResult Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline  ::uint32_t getJoinId();
  inline void setJoinId( ::uint32_t value);

  inline bool getSucceeded();
  inline void setSucceeded(bool value);

  inline bool hasCap();
#if !ZAP_LITE
  inline  ::zap::Capability::Client getCap();
  inline void setCap( ::zap::Capability::Client&& value);
  inline void setCap( ::zap::Capability::Client& value);
  inline void adoptCap(::zap::Orphan< ::zap::Capability>&& value);
  inline ::zap::Orphan< ::zap::Capability> disownCap();
#endif  // !ZAP_LITE

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class JoinResult::Pipeline {
public:
  typedef JoinResult Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::zap::Capability::Client getCap();
private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

inline  ::zap::rpc::twoparty::Side VatId::Reader::getSide() const {
  return _reader.getDataField< ::zap::rpc::twoparty::Side>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::zap::rpc::twoparty::Side VatId::Builder::getSide() {
  return _builder.getDataField< ::zap::rpc::twoparty::Side>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void VatId::Builder::setSide( ::zap::rpc::twoparty::Side value) {
  _builder.setDataField< ::zap::rpc::twoparty::Side>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline  ::uint32_t ThirdPartyCompletion::Reader::getJoinId() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::uint32_t ThirdPartyCompletion::Builder::getJoinId() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void ThirdPartyCompletion::Builder::setJoinId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline  ::uint32_t JoinKeyPart::Reader::getJoinId() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::uint32_t JoinKeyPart::Builder::getJoinId() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void JoinKeyPart::Builder::setJoinId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline  ::uint16_t JoinKeyPart::Reader::getPartCount() const {
  return _reader.getDataField< ::uint16_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS);
}

inline  ::uint16_t JoinKeyPart::Builder::getPartCount() {
  return _builder.getDataField< ::uint16_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS);
}
inline void JoinKeyPart::Builder::setPartCount( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      ::zap::bounded<2>() * ::zap::ELEMENTS, value);
}

inline  ::uint16_t JoinKeyPart::Reader::getPartNum() const {
  return _reader.getDataField< ::uint16_t>(
      ::zap::bounded<3>() * ::zap::ELEMENTS);
}

inline  ::uint16_t JoinKeyPart::Builder::getPartNum() {
  return _builder.getDataField< ::uint16_t>(
      ::zap::bounded<3>() * ::zap::ELEMENTS);
}
inline void JoinKeyPart::Builder::setPartNum( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      ::zap::bounded<3>() * ::zap::ELEMENTS, value);
}

inline  ::uint32_t JoinResult::Reader::getJoinId() const {
  return _reader.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::uint32_t JoinResult::Builder::getJoinId() {
  return _builder.getDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void JoinResult::Builder::setJoinId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline bool JoinResult::Reader::getSucceeded() const {
  return _reader.getDataField<bool>(
      ::zap::bounded<32>() * ::zap::ELEMENTS);
}

inline bool JoinResult::Builder::getSucceeded() {
  return _builder.getDataField<bool>(
      ::zap::bounded<32>() * ::zap::ELEMENTS);
}
inline void JoinResult::Builder::setSucceeded(bool value) {
  _builder.setDataField<bool>(
      ::zap::bounded<32>() * ::zap::ELEMENTS, value);
}

inline bool JoinResult::Reader::hasCap() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool JoinResult::Builder::hasCap() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
#if !ZAP_LITE
inline  ::zap::Capability::Client JoinResult::Reader::getCap() const {
  return ::zap::_::PointerHelpers< ::zap::Capability>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Capability::Client JoinResult::Builder::getCap() {
  return ::zap::_::PointerHelpers< ::zap::Capability>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Capability::Client JoinResult::Pipeline::getCap() {
  return  ::zap::Capability::Client(_typeless.getPointerField(0).asCap());
}
inline void JoinResult::Builder::setCap( ::zap::Capability::Client&& cap) {
  ::zap::_::PointerHelpers< ::zap::Capability>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(cap));
}
inline void JoinResult::Builder::setCap( ::zap::Capability::Client& cap) {
  ::zap::_::PointerHelpers< ::zap::Capability>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), cap);
}
inline void JoinResult::Builder::adoptCap(
    ::zap::Orphan< ::zap::Capability>&& value) {
  ::zap::_::PointerHelpers< ::zap::Capability>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Capability> JoinResult::Builder::disownCap() {
  return ::zap::_::PointerHelpers< ::zap::Capability>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
#endif  // !ZAP_LITE

}  // namespace
}  // namespace
}  // namespace

ZAP_END_HEADER

