// Generated by Zap compiler, DO NOT EDIT
// source: stream.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(995f9a3377c0b16e);

}  // namespace schemas
}  // namespace zap

namespace zap {

struct StreamResult {
  StreamResult() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(995f9a3377c0b16e, 0, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

class StreamResult::Reader {
public:
  typedef StreamResult Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class StreamResult::Builder {
public:
  typedef StreamResult Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class StreamResult::Pipeline {
public:
  typedef StreamResult Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

}  // namespace

ZAP_END_HEADER

