// Generated by Zap compiler, DO NOT EDIT
// source: json.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(a3fa7845f919dd83);
ZAP_DECLARE_SCHEMA(e31026e735d69ddf);
ZAP_DECLARE_SCHEMA(a0d9f6eca1c93d48);
ZAP_DECLARE_SCHEMA(fa5b1fd61c2e7c3d);
ZAP_DECLARE_SCHEMA(82d3e852af0336bf);
ZAP_DECLARE_SCHEMA(c4df13257bc2ea61);
ZAP_DECLARE_SCHEMA(cfa794e8d19a0162);
ZAP_DECLARE_SCHEMA(c2f8c20c293e5319);
ZAP_DECLARE_SCHEMA(d7d879450a253e4b);
ZAP_DECLARE_SCHEMA(f061e22f0ae5c7b5);
ZAP_DECLARE_SCHEMA(a0a054dea32fd98c);

}  // namespace schemas
}  // namespace zap

namespace zap {
namespace json {

struct Value {
  Value() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    NULL_,
    BOOLEAN,
    NUMBER,
    STRING,
    ARRAY,
    OBJECT,
    CALL,
    RAW,
  };
  struct Field;
  struct Call;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(a3fa7845f919dd83, 2, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Value::Field {
  Field() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(e31026e735d69ddf, 0, 2)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Value::Call {
  Call() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(a0d9f6eca1c93d48, 0, 2)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct FlattenOptions {
  FlattenOptions() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(c4df13257bc2ea61, 0, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct DiscriminatorOptions {
  DiscriminatorOptions() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(c2f8c20c293e5319, 0, 2)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

class Value::Reader {
public:
  typedef Value Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline Which which() const;
  inline bool isNull() const;
  inline  ::zap::Void getNull() const;

  inline bool isBoolean() const;
  inline bool getBoolean() const;

  inline bool isNumber() const;
  inline double getNumber() const;

  inline bool isString() const;
  inline bool hasString() const;
  inline  ::zap::Text::Reader getString() const;

  inline bool isArray() const;
  inline bool hasArray() const;
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader getArray() const;

  inline bool isObject() const;
  inline bool hasObject() const;
  inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Reader getObject() const;

  inline bool isCall() const;
  inline bool hasCall() const;
  inline  ::zap::json::Value::Call::Reader getCall() const;

  inline bool isRaw() const;
  inline bool hasRaw() const;
  inline  ::zap::Text::Reader getRaw() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Value::Builder {
public:
  typedef Value Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline Which which();
  inline bool isNull();
  inline  ::zap::Void getNull();
  inline void setNull( ::zap::Void value = ::zap::VOID);

  inline bool isBoolean();
  inline bool getBoolean();
  inline void setBoolean(bool value);

  inline bool isNumber();
  inline double getNumber();
  inline void setNumber(double value);

  inline bool isString();
  inline bool hasString();
  inline  ::zap::Text::Builder getString();
  inline void setString( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initString(unsigned int size);
  inline void adoptString(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownString();

  inline bool isArray();
  inline bool hasArray();
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder getArray();
  inline void setArray( ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder initArray(unsigned int size);
  inline void adoptArray(::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>> disownArray();

  inline bool isObject();
  inline bool hasObject();
  inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Builder getObject();
  inline void setObject( ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Builder initObject(unsigned int size);
  inline void adoptObject(::zap::Orphan< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>> disownObject();

  inline bool isCall();
  inline bool hasCall();
  inline  ::zap::json::Value::Call::Builder getCall();
  inline void setCall( ::zap::json::Value::Call::Reader value);
  inline  ::zap::json::Value::Call::Builder initCall();
  inline void adoptCall(::zap::Orphan< ::zap::json::Value::Call>&& value);
  inline ::zap::Orphan< ::zap::json::Value::Call> disownCall();

  inline bool isRaw();
  inline bool hasRaw();
  inline  ::zap::Text::Builder getRaw();
  inline void setRaw( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initRaw(unsigned int size);
  inline void adoptRaw(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownRaw();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Value::Pipeline {
public:
  typedef Value Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Value::Field::Reader {
public:
  typedef Field Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasName() const;
  inline  ::zap::Text::Reader getName() const;

  inline bool hasValue() const;
  inline  ::zap::json::Value::Reader getValue() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Value::Field::Builder {
public:
  typedef Field Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasName();
  inline  ::zap::Text::Builder getName();
  inline void setName( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initName(unsigned int size);
  inline void adoptName(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownName();

  inline bool hasValue();
  inline  ::zap::json::Value::Builder getValue();
  inline void setValue( ::zap::json::Value::Reader value);
  inline  ::zap::json::Value::Builder initValue();
  inline void adoptValue(::zap::Orphan< ::zap::json::Value>&& value);
  inline ::zap::Orphan< ::zap::json::Value> disownValue();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Value::Field::Pipeline {
public:
  typedef Field Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::zap::json::Value::Pipeline getValue();
private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Value::Call::Reader {
public:
  typedef Call Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasFunction() const;
  inline  ::zap::Text::Reader getFunction() const;

  inline bool hasParams() const;
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader getParams() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Value::Call::Builder {
public:
  typedef Call Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasFunction();
  inline  ::zap::Text::Builder getFunction();
  inline void setFunction( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initFunction(unsigned int size);
  inline void adoptFunction(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownFunction();

  inline bool hasParams();
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder getParams();
  inline void setParams( ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader value);
  inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder initParams(unsigned int size);
  inline void adoptParams(::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>&& value);
  inline ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>> disownParams();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Value::Call::Pipeline {
public:
  typedef Call Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class FlattenOptions::Reader {
public:
  typedef FlattenOptions Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasPrefix() const;
  inline  ::zap::Text::Reader getPrefix() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class FlattenOptions::Builder {
public:
  typedef FlattenOptions Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasPrefix();
  inline  ::zap::Text::Builder getPrefix();
  inline void setPrefix( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initPrefix(unsigned int size);
  inline void adoptPrefix(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownPrefix();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class FlattenOptions::Pipeline {
public:
  typedef FlattenOptions Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class DiscriminatorOptions::Reader {
public:
  typedef DiscriminatorOptions Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasName() const;
  inline  ::zap::Text::Reader getName() const;

  inline bool hasValueName() const;
  inline  ::zap::Text::Reader getValueName() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class DiscriminatorOptions::Builder {
public:
  typedef DiscriminatorOptions Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasName();
  inline  ::zap::Text::Builder getName();
  inline void setName( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initName(unsigned int size);
  inline void adoptName(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownName();

  inline bool hasValueName();
  inline  ::zap::Text::Builder getValueName();
  inline void setValueName( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initValueName(unsigned int size);
  inline void adoptValueName(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownValueName();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class DiscriminatorOptions::Pipeline {
public:
  typedef DiscriminatorOptions Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

inline  ::zap::json::Value::Which Value::Reader::which() const {
  return _reader.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline  ::zap::json::Value::Which Value::Builder::which() {
  return _builder.getDataField<Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline bool Value::Reader::isNull() const {
  return which() == Value::NULL_;
}
inline bool Value::Builder::isNull() {
  return which() == Value::NULL_;
}
inline  ::zap::Void Value::Reader::getNull() const {
  KJ_IREQUIRE((which() == Value::NULL_),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::zap::Void Value::Builder::getNull() {
  KJ_IREQUIRE((which() == Value::NULL_),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void Value::Builder::setNull( ::zap::Void value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::NULL_);
  _builder.setDataField< ::zap::Void>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline bool Value::Reader::isBoolean() const {
  return which() == Value::BOOLEAN;
}
inline bool Value::Builder::isBoolean() {
  return which() == Value::BOOLEAN;
}
inline bool Value::Reader::getBoolean() const {
  KJ_IREQUIRE((which() == Value::BOOLEAN),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField<bool>(
      ::zap::bounded<16>() * ::zap::ELEMENTS);
}

inline bool Value::Builder::getBoolean() {
  KJ_IREQUIRE((which() == Value::BOOLEAN),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField<bool>(
      ::zap::bounded<16>() * ::zap::ELEMENTS);
}
inline void Value::Builder::setBoolean(bool value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::BOOLEAN);
  _builder.setDataField<bool>(
      ::zap::bounded<16>() * ::zap::ELEMENTS, value);
}

inline bool Value::Reader::isNumber() const {
  return which() == Value::NUMBER;
}
inline bool Value::Builder::isNumber() {
  return which() == Value::NUMBER;
}
inline double Value::Reader::getNumber() const {
  KJ_IREQUIRE((which() == Value::NUMBER),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}

inline double Value::Builder::getNumber() {
  KJ_IREQUIRE((which() == Value::NUMBER),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS);
}
inline void Value::Builder::setNumber(double value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::NUMBER);
  _builder.setDataField<double>(
      ::zap::bounded<1>() * ::zap::ELEMENTS, value);
}

inline bool Value::Reader::isString() const {
  return which() == Value::STRING;
}
inline bool Value::Builder::isString() {
  return which() == Value::STRING;
}
inline bool Value::Reader::hasString() const {
  if (which() != Value::STRING) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Builder::hasString() {
  if (which() != Value::STRING) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Value::Reader::getString() const {
  KJ_IREQUIRE((which() == Value::STRING),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Value::Builder::getString() {
  KJ_IREQUIRE((which() == Value::STRING),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::setString( ::zap::Text::Reader value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::STRING);
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Value::Builder::initString(unsigned int size) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::STRING);
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Builder::adoptString(
    ::zap::Orphan< ::zap::Text>&& value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::STRING);
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Value::Builder::disownString() {
  KJ_IREQUIRE((which() == Value::STRING),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Reader::isArray() const {
  return which() == Value::ARRAY;
}
inline bool Value::Builder::isArray() {
  return which() == Value::ARRAY;
}
inline bool Value::Reader::hasArray() const {
  if (which() != Value::ARRAY) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Builder::hasArray() {
  if (which() != Value::ARRAY) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader Value::Reader::getArray() const {
  KJ_IREQUIRE((which() == Value::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder Value::Builder::getArray() {
  KJ_IREQUIRE((which() == Value::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::setArray( ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::ARRAY);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder Value::Builder::initArray(unsigned int size) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::ARRAY);
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Builder::adoptArray(
    ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>&& value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::ARRAY);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>> Value::Builder::disownArray() {
  KJ_IREQUIRE((which() == Value::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Reader::isObject() const {
  return which() == Value::OBJECT;
}
inline bool Value::Builder::isObject() {
  return which() == Value::OBJECT;
}
inline bool Value::Reader::hasObject() const {
  if (which() != Value::OBJECT) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Builder::hasObject() {
  if (which() != Value::OBJECT) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Reader Value::Reader::getObject() const {
  KJ_IREQUIRE((which() == Value::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Builder Value::Builder::getObject() {
  KJ_IREQUIRE((which() == Value::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::setObject( ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::OBJECT);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>::Builder Value::Builder::initObject(unsigned int size) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::OBJECT);
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Builder::adoptObject(
    ::zap::Orphan< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>&& value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::OBJECT);
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>> Value::Builder::disownObject() {
  KJ_IREQUIRE((which() == Value::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value::Field,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Reader::isCall() const {
  return which() == Value::CALL;
}
inline bool Value::Builder::isCall() {
  return which() == Value::CALL;
}
inline bool Value::Reader::hasCall() const {
  if (which() != Value::CALL) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Builder::hasCall() {
  if (which() != Value::CALL) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::json::Value::Call::Reader Value::Reader::getCall() const {
  KJ_IREQUIRE((which() == Value::CALL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::json::Value::Call>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::json::Value::Call::Builder Value::Builder::getCall() {
  KJ_IREQUIRE((which() == Value::CALL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::json::Value::Call>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::setCall( ::zap::json::Value::Call::Reader value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::CALL);
  ::zap::_::PointerHelpers< ::zap::json::Value::Call>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::json::Value::Call::Builder Value::Builder::initCall() {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::CALL);
  return ::zap::_::PointerHelpers< ::zap::json::Value::Call>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::adoptCall(
    ::zap::Orphan< ::zap::json::Value::Call>&& value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::CALL);
  ::zap::_::PointerHelpers< ::zap::json::Value::Call>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::json::Value::Call> Value::Builder::disownCall() {
  KJ_IREQUIRE((which() == Value::CALL),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::json::Value::Call>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Reader::isRaw() const {
  return which() == Value::RAW;
}
inline bool Value::Builder::isRaw() {
  return which() == Value::RAW;
}
inline bool Value::Reader::hasRaw() const {
  if (which() != Value::RAW) return false;
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Builder::hasRaw() {
  if (which() != Value::RAW) return false;
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Value::Reader::getRaw() const {
  KJ_IREQUIRE((which() == Value::RAW),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Value::Builder::getRaw() {
  KJ_IREQUIRE((which() == Value::RAW),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Builder::setRaw( ::zap::Text::Reader value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::RAW);
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Value::Builder::initRaw(unsigned int size) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::RAW);
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Builder::adoptRaw(
    ::zap::Orphan< ::zap::Text>&& value) {
  _builder.setDataField<Value::Which>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, Value::RAW);
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Value::Builder::disownRaw() {
  KJ_IREQUIRE((which() == Value::RAW),
              "Must check which() before get()ing a union member.");
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Field::Reader::hasName() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Field::Builder::hasName() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Value::Field::Reader::getName() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Value::Field::Builder::getName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Field::Builder::setName( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Value::Field::Builder::initName(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Field::Builder::adoptName(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Value::Field::Builder::disownName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Field::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool Value::Field::Builder::hasValue() {
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::json::Value::Reader Value::Field::Reader::getValue() const {
  return ::zap::_::PointerHelpers< ::zap::json::Value>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::json::Value::Builder Value::Field::Builder::getValue() {
  return ::zap::_::PointerHelpers< ::zap::json::Value>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
#if !ZAP_LITE
inline  ::zap::json::Value::Pipeline Value::Field::Pipeline::getValue() {
  return  ::zap::json::Value::Pipeline(_typeless.getPointerField(1));
}
#endif  // !ZAP_LITE
inline void Value::Field::Builder::setValue( ::zap::json::Value::Reader value) {
  ::zap::_::PointerHelpers< ::zap::json::Value>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::json::Value::Builder Value::Field::Builder::initValue() {
  return ::zap::_::PointerHelpers< ::zap::json::Value>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void Value::Field::Builder::adoptValue(
    ::zap::Orphan< ::zap::json::Value>&& value) {
  ::zap::_::PointerHelpers< ::zap::json::Value>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::json::Value> Value::Field::Builder::disownValue() {
  return ::zap::_::PointerHelpers< ::zap::json::Value>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

inline bool Value::Call::Reader::hasFunction() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Value::Call::Builder::hasFunction() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Value::Call::Reader::getFunction() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Value::Call::Builder::getFunction() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Value::Call::Builder::setFunction( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Value::Call::Builder::initFunction(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Value::Call::Builder::adoptFunction(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Value::Call::Builder::disownFunction() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Value::Call::Reader::hasParams() const {
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool Value::Call::Builder::hasParams() {
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader Value::Call::Reader::getParams() const {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder Value::Call::Builder::getParams() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void Value::Call::Builder::setParams( ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Reader value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>::Builder Value::Call::Builder::initParams(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), size);
}
inline void Value::Call::Builder::adoptParams(
    ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>&& value) {
  ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>> Value::Call::Builder::disownParams() {
  return ::zap::_::PointerHelpers< ::zap::List< ::zap::json::Value,  ::zap::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

inline bool FlattenOptions::Reader::hasPrefix() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool FlattenOptions::Builder::hasPrefix() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader FlattenOptions::Reader::getPrefix() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS),
        ::zap::schemas::bp_c4df13257bc2ea61 + 35);
}
inline  ::zap::Text::Builder FlattenOptions::Builder::getPrefix() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS),
        ::zap::schemas::bp_c4df13257bc2ea61 + 35);
}
inline void FlattenOptions::Builder::setPrefix( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder FlattenOptions::Builder::initPrefix(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void FlattenOptions::Builder::adoptPrefix(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> FlattenOptions::Builder::disownPrefix() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool DiscriminatorOptions::Reader::hasName() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool DiscriminatorOptions::Builder::hasName() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader DiscriminatorOptions::Reader::getName() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder DiscriminatorOptions::Builder::getName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void DiscriminatorOptions::Builder::setName( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder DiscriminatorOptions::Builder::initName(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void DiscriminatorOptions::Builder::adoptName(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> DiscriminatorOptions::Builder::disownName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool DiscriminatorOptions::Reader::hasValueName() const {
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool DiscriminatorOptions::Builder::hasValueName() {
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader DiscriminatorOptions::Reader::getValueName() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder DiscriminatorOptions::Builder::getValueName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void DiscriminatorOptions::Builder::setValueName( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder DiscriminatorOptions::Builder::initValueName(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), size);
}
inline void DiscriminatorOptions::Builder::adoptValueName(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> DiscriminatorOptions::Builder::disownValueName() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

}  // namespace
}  // namespace

ZAP_END_HEADER

